Linux userspace toolchain file
Signed-off-by: Bamvor Jian ZHANG <bamv2005@gmail.com>

Support rv64: platform init

1.  share memory uio
2.  replace unix socket based ipi to uio based ipi
3.  define _rproc_wait
4.  remove linux_proc_io_ops
5.  remove platform_slave_setup_resource_table
6.  Skip setting resource table to remoteproc
7.  update share memory addr

Signed-off-by: Bamvor Jian ZHANG <bamv2005@gmail.com>

Allow load firmware build as shared

When load_fw built as static, it make use of the memory map for
xilinx platform. Such map is not suitable for rv64 virt platform.

This patch address this issue by enable building load_fw as shared
executable. This work is precondition of #15.

Signed-off-by: Bamvor Jian ZHANG <bamv2005@gmail.com>

Platform support for load_fw testcase

1.  Seperate zynqmp and rv64 virt platform
2.  define WITH_WFI to make load_fw buildable in x86 Linux
3.  Add virt_rv64_rproc_example.c to handle rv64 cpu ops
4.  Add build_rv64_Linux.sh for building rv64 Linux userspace open-amp
    with load_fw testcase

This the beginning of #15.

Signed-off-by: Bamvor Jian ZHANG <bamv2005@gmail.com>

load_fw: support load from file

There are three steps in #15:
1.  read rtthread.elf from file and parse. This patch.
2.  mmap the rtthread load address. Next patch.
3.  start the rtthread from the address parsed from step 1.

This patch read elf of remote processsor to memory. The output is
```
Loading Exectuable Demo
metal: debug:     added page size 4096 @/tmp
apu_rproc_init: node id: 1
Start to load executable with remoteproc_load()
metal: debug:     remoteproc_load: check remoteproc status
metal: debug:     remoteproc_load: open executable image
file size 1397552
1397552 read
metal: debug:     remoteproc_load: check loader
metal: debug:     remoteproc_load: loading headers
metal: debug:     Loading ELF headering
metal: debug:     Loading ELF program header.
metal: debug:     Loading ELF section header.
metal: debug:     Loading ELF section header complete.
metal: debug:     Loading ELF shstrtab.
metal: debug:     remoteproc_load, load header 0x0, 0x155330, next 0x15148, 0x0
metal: debug:     remoteproc_load: load executable data
metal: debug:     segment: 1, total segs 1
metal: debug:     load data: da 0x90200000, offset 0x1000, len = 0x3f03c, memsize = 0x44a84, state 0x20801
```

We could see that open-amp get the right address(AKA: 0x90200000)
which will be used by mmap callback.

Signed-off-by: Bamvor Jian ZHANG <bamv2005@gmail.com>

rproc: manage io region of remote proc through libmetal

This patch looks for the rproc in device tree through libmetal in
Linux.

Signed-off-by: Bamvor Jian ZHANG <bamv2005@gmail.com>

quirk: add rv64 Linux build quirk

Signed-off-by: Bamvor Jian ZHANG <bamv2005@gmail.com>

script: helper for run open-amp

Signed-off-by: Bamvor Jian ZHANG <bamv2005@gmail.com>

Fix wrong image base

mem_image_store make use of image->base as the load address of the
image of remote processor. It should be set in order to copy the data
to real start address for remote processor.

This patch fix the missing base. After this work. Only the start ops
is missing for task #15.

Signed-off-by: Bamvor Jian ZHANG <bamv2005@gmail.com>

build with debug info

Signed-off-by: Bamvor Jian ZHANG <bamv2005@gmail.com>

Start add Linux rv64 support

1. Add platform info.c/h
2. Add init_system
3. Add rv64_virt_linux_proc.c for rv64_virt process ops

Signed-off-by: Bamvor Jian ZHANG <bamv2005@gmail.com>

debug: disable all the ipi relative code

```
metal: info:      metal_uio_dev_open: No IRQ for device 90000000.shm.
Successfully open shm device.uio': ./build/usr/local/bin/msg-test-rpmsg-ping-shar
metal: info:      metal_uio_dev_open: No IRQ for device 90180000.shm.
Successfully open shm poll device.
Successfully added shared memory
Successfully initialized remoteproc.
Successfully initialized remoteproc
Calling mmap resource table.
Successfully mmap resource table.
Failed to intialize remoteproc
Failed to create remoteproc device.
ERROR: Failed to initialize platform.
Stopping application...
```

Signed-off-by: Bamvor Jian ZHANG <bamv2005@gmail.com>

set resource table

Signed-off-by: Bamvor Jian ZHANG <bamv2005@gmail.com>

update share memory address

Signed-off-by: Bamvor Jian ZHANG <bamv2005@gmail.com>

Fix: seperate shared memory and ring rx/tx

Signed-off-by: Bamvor Jian ZHANG <bamv2005@gmail.com>

add riscv rtt

Signed-off-by: Bamvor Jian ZHANG <bamv2005@gmail.com>

rv64: add makefiles

Signed-off-by: Bamvor Jian ZHANG <bamv2005@gmail.com>

build: set Generic/riscv

Signed-off-by: Bamvor Jian ZHANG <bamv2005@gmail.com>

Add support for compiling rtt

Signed-off-by: Bamvor Jian ZHANG <bamv2005@gmail.com>

try to fix metal_device_open

Signed-off-by: Bamvor Jian ZHANG <bamv2005@gmail.com>

Fix the wrong addr and size of rsc_table

Signed-off-by: Bamvor Jian ZHANG <bamv2005@gmail.com>

Fix: keep NO_RESOURCE_ENTRIES as same as rtt side

Signed-off-by: Bamvor Jian ZHANG <bamv2005@gmail.com>

fix: quirk: add rv64 Linux build quirk

Signed-off-by: Bamvor Jian ZHANG <bamv2005@gmail.com>

Fix for upstream: add miss mutex deinit to avoid rtt assertion

Signed-off-by: Bamvor Jian ZHANG <bamv2005@gmail.com>

rtt: clear the bss variable

As rt-thread will not clear the per-command bss segment.

This is part of work for issue #17.

Signed-off-by: Bamvor Jian ZHANG <bamv2005@gmail.com>

update platform_release_rpmsg_vdev according to upstream

Signed-off-by: Bamvor Jian ZHANG <bamv2005@gmail.com>

Add remoteproc start, stop and shutdown for load_fw testcase

Signed-off-by: Bamvor Jian ZHANG <bamv2005@gmail.com>

link libsysfs for accessing opensbi

Signed-off-by: Bamvor Jian ZHANG <bamv2005@gmail.com>

Fix failing to re-run

issue #27

The reason is that the count is not cleared. It should be cleared by
OS. But it seems that rt-thread do not. The commit fix this by
manually resetting the count variable.

Test 5 times and all pass.

Signed-off-by: Bamvor Jian ZHANG <bamv2005@gmail.com>

update cross compile file

Signed-off-by: Bamvor Jian ZHANG <bamv2005@gmail.com>

build: add libsysfs dependency for load_fw

Signed-off-by: Bamvor Jian ZHANG <bamv2005@gmail.com>

build: enable build load_fw for rv64 machine

Signed-off-by: Bamvor Jian ZHANG <bamv2005@gmail.com>

build: remote CMAKE_C_FLAGS which will be passed from commandline

Signed-off-by: Bamvor Jian ZHANG <bamv2005@gmail.com>

build: remove useless and wrong c++ cross-compiler

Signed-off-by: Bamvor Jian ZHANG <bamv2005@gmail.com>

set cpu offline

Signed-off-by: Bamvor Jian ZHANG <bamv2005@gmail.com>

riscv64: bypass noblock load

Signed-off-by: Bamvor ZHANG <bamv2005@gmail.com>

rv64: add toolchain prefix for buildroot toolchain

Signed-off-by: Bamvor ZHANG <bamv2005@gmail.com>

Fixes: set cpu offline

1.  Allow unplug cpu fail(for the cpu is not managed by Linux")
2.  stop cpu through openSBI driver.

Signed-off-by: Bamvor ZHANG <bamv2005@gmail.com>

Fix warning

Signed-off-by: Bamvor ZHANG <bamv2005@gmail.com>

rv64: do not stop and shutdown the remoteproc directly

Signed-off-by: Bamvor ZHANG <bamv2005@gmail.com>

rv64:load_fw: improve error return

Signed-off-by: Bamvor ZHANG <bamv2005@gmail.com>

remoteproc: rv64: fixes: do not free the memory which could not be freed

Signed-off-by: Bamvor ZHANG <bamv2005@gmail.com>

remoteproc: support shuting down remote proc by signal

Signed-off-by: Bamvor ZHANG <bamv2005@gmail.com>

rtt irq

Signed-off-by: Bamvor ZHANG <bamv2005@gmail.com>

rpmsg irq

Signed-off-by: Bamvor ZHANG <bamv2005@gmail.com>

Revert "rpmsg irq"

This reverts commit b0605574e13af8557dcea6006f0cb5672978f086.

Revert "rtt irq"

This reverts commit f45d120e44953d3f4452189e122a33bb70414d46.